/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author pittu
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        iniciadorEstilos();
    }
    
    private void iniciadorEstilos() {
        
        bienvenido.putClientProperty( "FlatLaf.style", "font: $h2.font" );
        bienvenido.setForeground(Color.BLACK);
        linea1.putClientProperty( "FlatLaf.style", "font: large regular.font" );
        linea1.setForeground(Color.BLACK);
        linea2.putClientProperty( "FlatLaf.style", "font: large regular.font" );
        linea2.setForeground(Color.BLACK);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoInicio = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        linea1 = new javax.swing.JLabel();
        linea2 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        fondoInicio.setBackground(new java.awt.Color(255, 255, 255));
        fondoInicio.setPreferredSize(new java.awt.Dimension(557, 445));

        bienvenido.setText("¡Bienvenido!");

        linea1.setText("Este es el conversor de unidades desarrollado para el Challenges Back End ONE - G5.");

        linea2.setText("Fue desarrollado para convertir entre monedas, longitud, tiempo y temperatura.");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondo inicio.jpg"))); // NOI18N
        imagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagen.setPreferredSize(new java.awt.Dimension(557, 445));

        javax.swing.GroupLayout fondoInicioLayout = new javax.swing.GroupLayout(fondoInicio);
        fondoInicio.setLayout(fondoInicioLayout);
        fondoInicioLayout.setHorizontalGroup(
            fondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoInicioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(fondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienvenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        fondoInicioLayout.setVerticalGroup(
            fondoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoInicioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(linea1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(linea2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenido;
    private javax.swing.JPanel fondoInicio;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel linea1;
    private javax.swing.JLabel linea2;
    // End of variables declaration//GEN-END:variables
}



