/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.challengeoneconversor.servicios.ServicioConversor;
import java.awt.Color;

/**
 *
 * @author pittu
 */
public class Moneda extends javax.swing.JPanel {

    ServicioConversor servicio = new ServicioConversor();

    /**
     * Creates new form Inicio
     */
    public Moneda() {
        initComponents();
        iniciadorEstilos();
    }

    private void iniciadorEstilos() {

        linea1.putClientProperty("FlatLaf.style", "font: $h3.font");
        linea1.setForeground(Color.BLACK);
        linea2.putClientProperty("FlatLaf.style", "font: $h3.font");
        linea2.setForeground(Color.BLACK);
        resultado.putClientProperty("FlatLaf.style", "font: 35 bold.font");
        resultado.setForeground(Color.BLACK);
//        linea2.putClientProperty( "FlatLaf.style", "font: large regular.font" );
//        linea2.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoMoneda = new javax.swing.JPanel();
        calcular = new javax.swing.JButton();
        linea1 = new javax.swing.JLabel();
        opcionConversion = new javax.swing.JComboBox<>();
        linea2 = new javax.swing.JLabel();
        cantidadAConvertir = new javax.swing.JTextField();
        resultado = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        fondoMoneda.setBackground(new java.awt.Color(255, 255, 255));
        fondoMoneda.setPreferredSize(new java.awt.Dimension(557, 445));

        calcular.setBackground(new java.awt.Color(1, 166, 228));
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("Calcular");
        calcular.setBorder(null);
        calcular.setBorderPainted(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        linea1.setText("Selecciona una opción de conversión.");

        opcionConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos Chilenos a Dólar", "Pesos Chilenos a Euros", "Pesos Chilenos a Libras Esterlinas", "Pesos Chilenos a Yen Japonés", "Pesos Chilenos a Won Sur-coreano", "-------------------------------------", "Dólar a Pesos Chilenos", "Euros a Pesos Chilenos", "Libras Esterlinas a Pesos Chilenos", "Yen Japonés a Pesos Chilenos", "Won Sur-coreano a Pesos Chilenos" }));

        linea2.setText("Ingrese la cantidad de dinero que desea convertir (Solo números)");

        cantidadAConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadAConvertirKeyTyped(evt);
            }
        });

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen monedas.png"))); // NOI18N
        imagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        imagen.setPreferredSize(new java.awt.Dimension(557, 445));
        imagen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout fondoMonedaLayout = new javax.swing.GroupLayout(fondoMoneda);
        fondoMoneda.setLayout(fondoMonedaLayout);
        fondoMonedaLayout.setHorizontalGroup(
            fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcionConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoMonedaLayout.createSequentialGroup()
                        .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(160, 160, 160)))
                .addGap(7, 7, 7))
        );
        fondoMonedaLayout.setVerticalGroup(
            fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(linea1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(opcionConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(linea2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(cantidadAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoMonedaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 250, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadAConvertirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadAConvertirKeyTyped
        //validamos que se ingrese solo numeroa  traves de nuestro metodo "Validar double"
        servicio.validarDouble(evt, cantidadAConvertir);        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadAConvertirKeyTyped

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        Double cantidad = Double.valueOf(cantidadAConvertir.getText());
        int opcion=opcionConversion.getSelectedIndex();
        resultado.setText(servicio.calcularCambio(opcion,cantidad));
    }//GEN-LAST:event_calcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cantidadAConvertir;
    private javax.swing.JPanel fondoMoneda;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel linea1;
    private javax.swing.JLabel linea2;
    private javax.swing.JComboBox<String> opcionConversion;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
