/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;


import com.mycompany.challengeoneconversor.servicios.ServicioConversor;
import java.awt.Color;

/**
 *
 * @author pittu
 */
public class Temperatura extends javax.swing.JPanel {

    ServicioConversor servicio = new ServicioConversor();
    

    /**
     * Creates new form Inicio
     */
    public Temperatura() {
        initComponents();
        iniciadorEstilos();

    }

    private void iniciadorEstilos() {

        
        linea1.putClientProperty("FlatLaf.style", "font: $h3.font");
        linea1.setForeground(Color.BLACK);
        linea2.putClientProperty("FlatLaf.style", "font: $h3.font");
        linea2.setForeground(Color.BLACK);
        resultado.putClientProperty("FlatLaf.style", "font: 35 bold.font");
        resultado.setForeground(Color.BLACK);
//        linea2.putClientProperty( "FlatLaf.style", "font: large regular.font" );
//        linea2.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoMoneda = new javax.swing.JPanel();
        resultado = new javax.swing.JLabel();
        linea1 = new javax.swing.JLabel();
        opcionConversion = new javax.swing.JComboBox<>();
        linea2 = new javax.swing.JLabel();
        cantidadAConvertir = new javax.swing.JTextField();
        calcular = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        fondoMoneda.setBackground(new java.awt.Color(255, 255, 255));
        fondoMoneda.setPreferredSize(new java.awt.Dimension(557, 445));

        linea1.setText("Selecciona una opción de conversión.");

        opcionConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius (°C) a Fahrenheit (°F)", "Celsius (°C) a Kelvin (K)", "------------------------------", "Fahrenheit (°F) a Celsius (°C)", "Fahrenheit (°F) a Kelvin (K)", "------------------------------", "Kelvin (K) a Celsius (°C)", "Kelvin (K) a Fahrenheit (°F)" }));
        opcionConversion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opcionConversionItemStateChanged(evt);
            }
        });
        opcionConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConversionActionPerformed(evt);
            }
        });

        linea2.setText("Ingrese la temperatura que desea convertir (Solo números)");

        cantidadAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadAConvertirActionPerformed(evt);
            }
        });
        cantidadAConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadAConvertirKeyTyped(evt);
            }
        });

        calcular.setBackground(new java.awt.Color(1, 166, 228));
        calcular.setForeground(new java.awt.Color(255, 255, 255));
        calcular.setText("Calcular");
        calcular.setBorder(null);
        calcular.setBorderPainted(false);
        calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen temperatura.png"))); // NOI18N
        imagen.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        imagen.setPreferredSize(new java.awt.Dimension(557, 445));
        imagen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout fondoMonedaLayout = new javax.swing.GroupLayout(fondoMoneda);
        fondoMoneda.setLayout(fondoMonedaLayout);
        fondoMonedaLayout.setHorizontalGroup(
            fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidadAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionConversion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoMonedaLayout.createSequentialGroup()
                        .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(160, 160, 160))
                    .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        fondoMonedaLayout.setVerticalGroup(
            fondoMonedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(linea2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cantidadAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(opcionConversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addGroup(fondoMonedaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(linea1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        Double cantidad = Double.valueOf(cantidadAConvertir.getText());
        int opcion=opcionConversion.getSelectedIndex();
        resultado.setText(servicio.calcularTemperatura(opcion,cantidad));

        
    }//GEN-LAST:event_calcularActionPerformed

    private void cantidadAConvertirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadAConvertirKeyTyped
        //validamos que se ingrese solo numeroa  traves de nuestro metodo "Validar double"
        servicio.validarDouble(evt, cantidadAConvertir);
    }//GEN-LAST:event_cantidadAConvertirKeyTyped

    private void opcionConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConversionActionPerformed
        
    }//GEN-LAST:event_opcionConversionActionPerformed

    private void cantidadAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadAConvertirActionPerformed


    }//GEN-LAST:event_cantidadAConvertirActionPerformed

    private void opcionConversionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opcionConversionItemStateChanged
            
    }//GEN-LAST:event_opcionConversionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cantidadAConvertir;
    private javax.swing.JPanel fondoMoneda;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel linea1;
    private javax.swing.JLabel linea2;
    private javax.swing.JComboBox<String> opcionConversion;
    private javax.swing.JLabel resultado;
    // End of variables declaration//GEN-END:variables
}
